-- ============================================================
-- REMOVED: This migration file is intentionally replaced by
-- the two committed Supabase-only migrations:
--   20260413225404_fix_fk_ownership_cross_ownership_rls_guards.sql
--   20260414024917_fix_rls_auth_initplan_lab_result_entries_interpreted_entries.sql
--
-- The RLS fixes described here were already applied on the hosted
-- project before this file was created. Applying this file would
-- create a duplicate migration entry.
--
-- This file is kept as a tombstone/comment only and performs no changes.
-- ============================================================
SELECT 1; -- tombstone, no-op
